- name: variables at task level
  hosts: localhost
  # these variables of parent or play level
  vars:
  - money: "100000 RS"
    land: "100 hectars"
  tasks:
  - name: inherent values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherent values from play and add and override
    vars:
    - money: "200000 RS"
      houses: "3 houses"
      ansible.builtin.debug:
        msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}"